import 'package:auto_route/auto_route.dart';
import 'package:fitlifts/services/providers/ads_provider.dart';
import 'package:fitlifts/services/providers/user_initial_details_provider.dart';
import 'package:fitlifts/core/constants/my_assets.dart';
import 'package:fitlifts/core/constants/my_colors.dart';
import 'package:fitlifts/presentation/utils.dart';
import 'package:fitlifts/presentation/common_widgets/divider_text.dart';
import 'package:fitlifts/presentation/common_widgets/explore_card.dart';
import 'package:fitlifts/presentation/common_widgets/refreshbar.dart';
import 'package:fitlifts/presentation/screens/general/controller_service.dart';
import 'package:fitlifts/presentation/screens/general/home/home_provider.dart';
import 'package:fitlifts/presentation/screens/general/home/home_widgets/stats_card.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:provider/provider.dart';
import '../../../../services/greetintgs.dart';
import '../../../routes/auto_router.gr.dart';

part "home.dart";
