name: fitlifts
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  loading_animation_widget: ^1.3.0
  persistent_bottom_nav_bar: ^6.2.1
  syncfusion_flutter_charts: ^28.2.12
  pedometer: ^4.0.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^11.4.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  intl: ^0.20.2
  auto_route: ^10.0.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  sensors_plus: ^6.1.1
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  flutter_animate: ^4.5.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  flutter_svg: ^2.0.17
  cloud_firestore: ^5.6.5
  razorpay_flutter: ^1.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants
  filename: my_assets.dart  