import 'dart:io';
import 'package:auto_route/auto_route.dart';
import 'package:fitlifts/presentation/common_widgets/circular_progress.dart';
import 'package:fitlifts/presentation/screens/auth/common_widgets/auth_title.dart';
import 'package:fitlifts/presentation/screens/auth/common_widgets/social_login_button.dart';
import 'package:fitlifts/presentation/screens/auth/register/register_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:provider/provider.dart';
import '../../../../core/constants/my_assets.dart';
import '../../../../core/constants/my_colors.dart';
import '../../../../core/utils/utils.dart';
import '../../../common_widgets/divider_text.dart';
import '../../../common_widgets/elevated_cta.dart';
import '../common_widgets/auth_bottom_bar.dart';
import '../common_widgets/credentials_text_field.dart';
import '../providers/social_login_provider.dart';

part "register.dart";
