// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9IEV42ObxqHe5sD3aiNjFeASLhbKxxY',
    appId: '1:782629770073:web:6c69fa20e56727e2b7f248',
    messagingSenderId: '782629770073',
    projectId: 'dropdesirefitlifts',
    authDomain: 'dropdesirefitlifts.firebaseapp.com',
    storageBucket: 'dropdesirefitlifts.firebasestorage.app',
    measurementId: 'G-T432RQF0R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZhEy7wRKV7vaWk0p9eKReTdy4pLR4MfM',
    appId: '1:782629770073:android:ac3f6a542a59a9e1b7f248',
    messagingSenderId: '782629770073',
    projectId: 'dropdesirefitlifts',
    storageBucket: 'dropdesirefitlifts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoMBtvpsPT5ULoU2LdzKU2CzS2sGcNzuM',
    appId: '1:782629770073:ios:0301351a74d071c0b7f248',
    messagingSenderId: '782629770073',
    projectId: 'dropdesirefitlifts',
    storageBucket: 'dropdesirefitlifts.firebasestorage.app',
    iosBundleId: 'com.dropdesire.fitlifts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoMBtvpsPT5ULoU2LdzKU2CzS2sGcNzuM',
    appId: '1:782629770073:ios:0301351a74d071c0b7f248',
    messagingSenderId: '782629770073',
    projectId: 'dropdesirefitlifts',
    storageBucket: 'dropdesirefitlifts.firebasestorage.app',
    iosBundleId: 'com.dropdesire.fitlifts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ9IEV42ObxqHe5sD3aiNjFeASLhbKxxY',
    appId: '1:782629770073:web:5d23d0e25f6d6c74b7f248',
    messagingSenderId: '782629770073',
    projectId: 'dropdesirefitlifts',
    authDomain: 'dropdesirefitlifts.firebaseapp.com',
    storageBucket: 'dropdesirefitlifts.firebasestorage.app',
    measurementId: 'G-8KP737QSEH',
  );

}