// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDofT-11DvjudtBLO1mefUbb-VhY4xf_o',
    appId: '1:333504318757:web:78cb14084cb7f45e7bdecc',
    messagingSenderId: '333504318757',
    projectId: 'fitlifts-b077d',
    authDomain: 'fitlifts-b077d.firebaseapp.com',
    storageBucket: 'fitlifts-b077d.firebasestorage.app',
    measurementId: 'G-1ZJVSYT0Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4TF3ZZe74onjp8VwDR7Wwpqtqc4b6H1U',
    appId: '1:333504318757:android:9886bc305462a51b7bdecc',
    messagingSenderId: '333504318757',
    projectId: 'fitlifts-b077d',
    storageBucket: 'fitlifts-b077d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3XdbzwMqU5td18N2TG8U3mYfCuuoVzFw',
    appId: '1:333504318757:ios:96aa4fd91d53b4997bdecc',
    messagingSenderId: '333504318757',
    projectId: 'fitlifts-b077d',
    storageBucket: 'fitlifts-b077d.firebasestorage.app',
    iosBundleId: 'com.example.fitlifts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3XdbzwMqU5td18N2TG8U3mYfCuuoVzFw',
    appId: '1:333504318757:ios:96aa4fd91d53b4997bdecc',
    messagingSenderId: '333504318757',
    projectId: 'fitlifts-b077d',
    storageBucket: 'fitlifts-b077d.firebasestorage.app',
    iosBundleId: 'com.example.fitlifts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDofT-11DvjudtBLO1mefUbb-VhY4xf_o',
    appId: '1:333504318757:web:dbcb9f1f9b3ab1047bdecc',
    messagingSenderId: '333504318757',
    projectId: 'fitlifts-b077d',
    authDomain: 'fitlifts-b077d.firebaseapp.com',
    storageBucket: 'fitlifts-b077d.firebasestorage.app',
    measurementId: 'G-EZW0KDFZQZ',
  );
}
